# ============================================================
# SAR DATASET STUDIO
# Ontología común
# ============================================================

classes: {}

aliases: {}

mapping_rules: {}